USE ROLE ACCOUNTADMIN;
CREATE DATABASE IF NOT EXISTS CASHLESSIQ COMMENT = 'CashlessIQ hackathon prototype';
GRANT OWNERSHIP ON DATABASE CASHLESSIQ TO ROLE CIQ_ADMIN COPY CURRENT GRANTS;

USE ROLE CIQ_ADMIN;
USE DATABASE CASHLESSIQ;

CREATE SCHEMA IF NOT EXISTS RAW COMMENT = 'Untouched source loads';
CREATE SCHEMA IF NOT EXISTS CORE COMMENT = 'Member and policy domain';
CREATE SCHEMA IF NOT EXISTS DOCS COMMENT = 'Documents, extracted facts, and rules';
CREATE SCHEMA IF NOT EXISTS AI COMMENT = 'Agent, search, semantic view, and tools';
CREATE SCHEMA IF NOT EXISTS APP COMMENT = 'Reviewer application and decisions';
CREATE SCHEMA IF NOT EXISTS GOV COMMENT = 'Governance policies and mappings';
CREATE SCHEMA IF NOT EXISTS EVAL COMMENT = 'Golden set and evaluation results';

CREATE FILE FORMAT IF NOT EXISTS RAW.CSV_FORMAT
  TYPE = CSV
  PARSE_HEADER = TRUE
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('', 'NULL');

CREATE STAGE IF NOT EXISTS DOCS.PREAUTH_STAGE
  DIRECTORY = (ENABLE = TRUE)
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
  COMMENT = 'Synthetic pre-authorisation PDFs';

CREATE STAGE IF NOT EXISTS DOCS.POLICY_STAGE
  DIRECTORY = (ENABLE = TRUE)
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
  COMMENT = 'Public policy wording PDFs';

CREATE STAGE IF NOT EXISTS APP.CIQ_APP_STAGE
  DIRECTORY = (ENABLE = TRUE)
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
  COMMENT = 'Streamlit application artifacts';

CREATE STAGE IF NOT EXISTS AI.CIQ_CODE_STAGE
  DIRECTORY = (ENABLE = TRUE)
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
  COMMENT = 'Versioned Python package for caller-rights rule procedures';

GRANT USAGE ON DATABASE CASHLESSIQ TO ROLE CIQ_APP_USER;
GRANT USAGE ON SCHEMA CASHLESSIQ.APP TO ROLE CIQ_APP_USER;
GRANT USAGE ON SCHEMA CASHLESSIQ.AI TO ROLE CIQ_APP_USER;
GRANT USAGE ON SCHEMA CASHLESSIQ.CORE TO ROLE CIQ_APP_USER;
GRANT USAGE ON SCHEMA CASHLESSIQ.DOCS TO ROLE CIQ_APP_USER;
GRANT USAGE ON SCHEMA CASHLESSIQ.EVAL TO ROLE CIQ_APP_USER;
GRANT READ ON STAGE CASHLESSIQ.APP.CIQ_APP_STAGE TO ROLE CIQ_APP_USER;

GRANT SELECT ON FUTURE TABLES IN SCHEMA CASHLESSIQ.CORE TO ROLE CIQ_APP_USER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CASHLESSIQ.DOCS TO ROLE CIQ_APP_USER;
GRANT SELECT, INSERT, UPDATE ON FUTURE TABLES IN SCHEMA CASHLESSIQ.APP TO ROLE CIQ_APP_USER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CASHLESSIQ.EVAL TO ROLE CIQ_APP_USER;
