USE ROLE CIQ_ADMIN;
USE DATABASE CASHLESSIQ;
USE SCHEMA CORE;

CREATE TABLE IF NOT EXISTS TPA (
  TPA_ID VARCHAR(20) NOT NULL PRIMARY KEY,
  NAME VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS HOSPITAL (
  HOSPITAL_ID VARCHAR(20) NOT NULL PRIMARY KEY,
  NAME VARCHAR(200) NOT NULL,
  CITY VARCHAR(100) NOT NULL,
  IS_NETWORK BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS POLICY_PRODUCT (
  PRODUCT_ID VARCHAR(40) NOT NULL PRIMARY KEY,
  PRODUCT_NAME VARCHAR(200) NOT NULL,
  INSURER VARCHAR(200) NOT NULL,
  UIN VARCHAR(100) NOT NULL,
  VERSION VARCHAR(50) NOT NULL,
  EFFECTIVE_FROM DATE NOT NULL,
  SOURCE_URL VARCHAR(1000) NOT NULL
);

CREATE TABLE IF NOT EXISTS MEMBER (
  MEMBER_ID VARCHAR(20) NOT NULL PRIMARY KEY,
  SYNTHEA_ID VARCHAR(100),
  FULL_NAME VARCHAR(200) NOT NULL,
  DOB DATE NOT NULL,
  GENDER VARCHAR(30) NOT NULL,
  CITY VARCHAR(100) NOT NULL,
  PHONE VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS POLICY (
  POLICY_ID VARCHAR(20) NOT NULL PRIMARY KEY,
  MEMBER_ID VARCHAR(20) NOT NULL REFERENCES MEMBER(MEMBER_ID),
  PRODUCT_ID VARCHAR(40) NOT NULL REFERENCES POLICY_PRODUCT(PRODUCT_ID),
  TPA_ID VARCHAR(20) NOT NULL REFERENCES TPA(TPA_ID),
  SUM_INSURED_INR NUMBER(12,0) NOT NULL,
  INCEPTION_DATE DATE NOT NULL,
  CONTINUOUS_COVER_SINCE DATE NOT NULL,
  CUMULATIVE_BONUS_INR NUMBER(12,0) NOT NULL DEFAULT 0,
  STATUS VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS MEMBER_CONDITION (
  MEMBER_ID VARCHAR(20) NOT NULL REFERENCES MEMBER(MEMBER_ID),
  ICD10_CODE VARCHAR(20) NOT NULL,
  CONDITION_NAME VARCHAR(200) NOT NULL,
  FIRST_DIAGNOSED_ON DATE NOT NULL,
  DECLARED_AT_PROPOSAL BOOLEAN NOT NULL,
  PRIMARY KEY (MEMBER_ID, ICD10_CODE)
);

CREATE TABLE IF NOT EXISTS CLAIM (
  CLAIM_ID VARCHAR(20) NOT NULL PRIMARY KEY,
  POLICY_ID VARCHAR(20) NOT NULL REFERENCES POLICY(POLICY_ID),
  ADMISSION_DATE DATE NOT NULL,
  DISCHARGE_DATE DATE,
  ICD10_CODE VARCHAR(20) NOT NULL,
  CLAIMED_INR NUMBER(12,0) NOT NULL,
  PAID_INR NUMBER(12,0) NOT NULL,
  STATUS VARCHAR(30) NOT NULL
);

