USE ROLE CIQ_ADMIN;
USE DATABASE CASHLESSIQ;
USE SCHEMA DOCS;

CREATE TABLE IF NOT EXISTS PREAUTH_REQUEST (
  REQUEST_ID VARCHAR(20) NOT NULL PRIMARY KEY,
  FILE_PATH VARCHAR(1000) NOT NULL,
  POLICY_ID VARCHAR(20) NOT NULL REFERENCES CASHLESSIQ.CORE.POLICY(POLICY_ID),
  HOSPITAL_ID VARCHAR(20) NOT NULL REFERENCES CASHLESSIQ.CORE.HOSPITAL(HOSPITAL_ID),
  RECEIVED_AT TIMESTAMP_TZ NOT NULL,
  STATUS VARCHAR(20) NOT NULL DEFAULT 'NEW'
    CHECK (STATUS IN ('NEW', 'DRAFTED', 'QUERIED', 'DECIDED'))
);

CREATE TABLE IF NOT EXISTS PREAUTH_FACTS (
  REQUEST_ID VARCHAR(20) NOT NULL PRIMARY KEY REFERENCES PREAUTH_REQUEST(REQUEST_ID),
  DIAGNOSIS VARCHAR(500),
  ICD10_CODE VARCHAR(20),
  PROCEDURE VARCHAR(500),
  IS_EMERGENCY BOOLEAN,
  ADMISSION_DATE DATE,
  PLANNED_LOS_DAYS NUMBER(5,0),
  ROOM_CATEGORY VARCHAR(100),
  ROOM_RENT_PER_DAY_INR NUMBER(12,0),
  ICU_DAYS NUMBER(5,0),
  COST_BREAKUP VARIANT,
  ESTIMATED_TOTAL_INR NUMBER(12,0),
  CLINICAL_NOTE VARCHAR,
  MISSING_FIELDS ARRAY,
  RAW_EXTRACT VARIANT
);

CREATE TABLE IF NOT EXISTS POLICY_CLAUSE (
  CLAUSE_ID VARCHAR(100) NOT NULL PRIMARY KEY,
  PRODUCT_ID VARCHAR(40) NOT NULL REFERENCES CASHLESSIQ.CORE.POLICY_PRODUCT(PRODUCT_ID),
  SECTION VARCHAR(100) NOT NULL,
  HEADING VARCHAR(500) NOT NULL,
  TEXT VARCHAR NOT NULL,
  PAGE NUMBER(6,0) NOT NULL
);

CREATE TABLE IF NOT EXISTS POLICY_RULE (
  RULE_ID VARCHAR(100) NOT NULL PRIMARY KEY,
  PRODUCT_ID VARCHAR(40) NOT NULL REFERENCES CASHLESSIQ.CORE.POLICY_PRODUCT(PRODUCT_ID),
  RULE_TYPE VARCHAR(50) NOT NULL CHECK (RULE_TYPE IN (
    'ROOM_RENT_CAP', 'ICU_CAP', 'PROCEDURE_SUBLIMIT', 'COPAY',
    'WAITING_INITIAL', 'WAITING_SPECIFIC', 'WAITING_PED', 'EXCLUSION',
    'PROPORTIONATE_DEDUCTION'
  )),
  PARAMS VARIANT NOT NULL,
  CLAUSE_ID VARCHAR(100) NOT NULL REFERENCES POLICY_CLAUSE(CLAUSE_ID),
  VERIFIED_BY VARCHAR(200),
  VERIFIED_AT TIMESTAMP_TZ
);

