USE ROLE CIQ_ADMIN;
USE DATABASE CASHLESSIQ;
USE WAREHOUSE CIQ_WH;

CREATE STAGE IF NOT EXISTS RAW.DATA_STAGE
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
  COMMENT = 'Fixed-seed synthetic CSV files';

-- PUT is a Snowflake CLI client command and paths resolve from the repository root.
PUT 'file://data_gen/output/*.csv' @RAW.DATA_STAGE
  AUTO_COMPRESS = FALSE OVERWRITE = TRUE;
PUT 'file://data_gen/output/preauth/*.pdf' @DOCS.PREAUTH_STAGE/preauth
  AUTO_COMPRESS = FALSE OVERWRITE = TRUE;
PUT 'file://data_gen/output/policy/*.pdf' @DOCS.POLICY_STAGE
  AUTO_COMPRESS = FALSE OVERWRITE = TRUE;

TRUNCATE TABLE EVAL.GOLDEN_CASE;
TRUNCATE TABLE DOCS.PREAUTH_FACTS;
TRUNCATE TABLE DOCS.PREAUTH_REQUEST;
TRUNCATE TABLE DOCS.POLICY_RULE;
TRUNCATE TABLE DOCS.POLICY_CLAUSE;
TRUNCATE TABLE CORE.CLAIM;
TRUNCATE TABLE CORE.MEMBER_CONDITION;
TRUNCATE TABLE CORE.POLICY;
TRUNCATE TABLE CORE.MEMBER;
TRUNCATE TABLE CORE.HOSPITAL;
TRUNCATE TABLE CORE.TPA;
TRUNCATE TABLE CORE.POLICY_PRODUCT;

COPY INTO CORE.TPA FROM @RAW.DATA_STAGE/tpa.csv
  FILE_FORMAT = (FORMAT_NAME = RAW.CSV_FORMAT) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
COPY INTO CORE.HOSPITAL FROM @RAW.DATA_STAGE/hospital.csv
  FILE_FORMAT = (FORMAT_NAME = RAW.CSV_FORMAT) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
COPY INTO CORE.POLICY_PRODUCT FROM @RAW.DATA_STAGE/policy_product.csv
  FILE_FORMAT = (FORMAT_NAME = RAW.CSV_FORMAT) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
COPY INTO CORE.MEMBER FROM @RAW.DATA_STAGE/member.csv
  FILE_FORMAT = (FORMAT_NAME = RAW.CSV_FORMAT) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
COPY INTO CORE.POLICY FROM @RAW.DATA_STAGE/policy.csv
  FILE_FORMAT = (FORMAT_NAME = RAW.CSV_FORMAT) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
COPY INTO CORE.MEMBER_CONDITION FROM @RAW.DATA_STAGE/member_condition.csv
  FILE_FORMAT = (FORMAT_NAME = RAW.CSV_FORMAT) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
COPY INTO CORE.CLAIM FROM @RAW.DATA_STAGE/claim.csv
  FILE_FORMAT = (FORMAT_NAME = RAW.CSV_FORMAT) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
COPY INTO DOCS.POLICY_CLAUSE FROM @RAW.DATA_STAGE/policy_clause.csv
  FILE_FORMAT = (FORMAT_NAME = RAW.CSV_FORMAT) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
CREATE OR REPLACE TEMP TABLE PREAUTH_REQUEST_LOAD (
  REQUEST_ID VARCHAR, FILE_PATH VARCHAR, POLICY_ID VARCHAR, HOSPITAL_ID VARCHAR,
  RECEIVED_AT VARCHAR, STATUS VARCHAR
);
COPY INTO PREAUTH_REQUEST_LOAD FROM @RAW.DATA_STAGE/preauth_request.csv
  FILE_FORMAT = (FORMAT_NAME = RAW.CSV_FORMAT) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
INSERT INTO DOCS.PREAUTH_REQUEST
SELECT REQUEST_ID, FILE_PATH, POLICY_ID, HOSPITAL_ID, TO_TIMESTAMP_TZ(RECEIVED_AT), STATUS
FROM PREAUTH_REQUEST_LOAD;

CREATE OR REPLACE TEMP TABLE RULE_LOAD (
  RULE_ID VARCHAR, PRODUCT_ID VARCHAR, RULE_TYPE VARCHAR, PARAMS VARCHAR,
  CLAUSE_ID VARCHAR, VERIFIED_BY VARCHAR, VERIFIED_AT VARCHAR
);
COPY INTO RULE_LOAD FROM @RAW.DATA_STAGE/policy_rule.csv
  FILE_FORMAT = (FORMAT_NAME = RAW.CSV_FORMAT) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
INSERT INTO DOCS.POLICY_RULE
SELECT RULE_ID, PRODUCT_ID, RULE_TYPE, PARSE_JSON(PARAMS), CLAUSE_ID, NULL, NULL
FROM RULE_LOAD;

CREATE OR REPLACE TEMP TABLE GOLDEN_LOAD (
  REQUEST_ID VARCHAR, EXPECTED_OUTCOME VARCHAR, EXPECTED_PAYABLE_INR VARCHAR,
  TOLERANCE_INR VARCHAR, EXPECTED_CLAUSE_IDS VARCHAR, TAGS VARCHAR
);
COPY INTO GOLDEN_LOAD FROM @RAW.DATA_STAGE/golden_case.csv
  FILE_FORMAT = (FORMAT_NAME = RAW.CSV_FORMAT) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
INSERT INTO EVAL.GOLDEN_CASE
SELECT REQUEST_ID, EXPECTED_OUTCOME, TRY_TO_NUMBER(EXPECTED_PAYABLE_INR),
       TO_NUMBER(TOLERANCE_INR), PARSE_JSON(EXPECTED_CLAUSE_IDS)::ARRAY,
       PARSE_JSON(TAGS)::ARRAY
FROM GOLDEN_LOAD;

ALTER STAGE DOCS.PREAUTH_STAGE REFRESH;
ALTER STAGE DOCS.POLICY_STAGE REFRESH;

SELECT 'TPA' ENTITY, COUNT(*) ROW_COUNT FROM CORE.TPA
UNION ALL SELECT 'HOSPITAL', COUNT(*) FROM CORE.HOSPITAL
UNION ALL SELECT 'MEMBER', COUNT(*) FROM CORE.MEMBER
UNION ALL SELECT 'POLICY', COUNT(*) FROM CORE.POLICY
UNION ALL SELECT 'MEMBER_CONDITION', COUNT(*) FROM CORE.MEMBER_CONDITION
UNION ALL SELECT 'CLAIM', COUNT(*) FROM CORE.CLAIM
UNION ALL SELECT 'PREAUTH_REQUEST', COUNT(*) FROM DOCS.PREAUTH_REQUEST
UNION ALL SELECT 'GOLDEN_CASE', COUNT(*) FROM EVAL.GOLDEN_CASE;
