USE ROLE CIQ_ADMIN;
USE DATABASE CASHLESSIQ;
USE SCHEMA AI;

CREATE OR REPLACE CORTEX SEARCH SERVICE CLAUSE_SEARCH
  ON TEXT
  PRIMARY KEY (CLAUSE_ID)
  ATTRIBUTES PRODUCT_ID, SECTION, HEADING
  WAREHOUSE = CIQ_WH
  TARGET_LAG = '1 day'
  EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
  REFRESH_MODE = INCREMENTAL
  INITIALIZE = ON_CREATE
  AUTO_SUSPEND = 1800
  COMMENT = 'Human-reviewed policy clauses filtered by product'
AS
SELECT CLAUSE_ID, PRODUCT_ID, SECTION, HEADING, TEXT, PAGE
FROM CASHLESSIQ.DOCS.POLICY_CLAUSE;

GRANT USAGE ON CORTEX SEARCH SERVICE CLAUSE_SEARCH TO ROLE CIQ_APP_USER;

SHOW CORTEX SEARCH SERVICES LIKE 'CLAUSE_SEARCH' IN SCHEMA CASHLESSIQ.AI;
