USE ROLE CIQ_ADMIN;
USE DATABASE CASHLESSIQ;
USE SCHEMA AI;

-- One row per policy keeps the five business metrics deterministic. Cortex
-- Analyst can still traverse the eight domain tables declared below for detail.
CREATE OR REPLACE VIEW POLICY_METRICS AS
WITH POLICY_YEAR AS (
  SELECT
    P.*,
    DATEADD(
      YEAR,
      DATEDIFF(YEAR, P.INCEPTION_DATE, CURRENT_DATE())
        - IFF(
            DATEADD(YEAR, DATEDIFF(YEAR, P.INCEPTION_DATE, CURRENT_DATE()), P.INCEPTION_DATE)
              > CURRENT_DATE(),
            1,
            0
          ),
      P.INCEPTION_DATE
    ) AS POLICY_YEAR_START
  FROM CASHLESSIQ.CORE.POLICY P
), CLAIM_TOTALS AS (
  SELECT
    PY.POLICY_ID,
    COALESCE(SUM(IFF(C.ADMISSION_DATE >= PY.POLICY_YEAR_START, C.PAID_INR, 0)), 0)
      AS SI_CONSUMED_INR,
    COUNT_IF(C.ADMISSION_DATE >= DATEADD(YEAR, -3, CURRENT_DATE())) AS CLAIMS_LAST_3Y
  FROM POLICY_YEAR PY
  LEFT JOIN CASHLESSIQ.CORE.CLAIM C ON C.POLICY_ID = PY.POLICY_ID
  GROUP BY PY.POLICY_ID
), CONDITION_TOTALS AS (
  SELECT MEMBER_ID, COUNT_IF(DECLARED_AT_PROPOSAL) AS DECLARED_PED_COUNT
  FROM CASHLESSIQ.CORE.MEMBER_CONDITION
  GROUP BY MEMBER_ID
)
SELECT
  PY.POLICY_ID,
  PY.MEMBER_ID,
  DATEDIFF(MONTH, PY.CONTINUOUS_COVER_SINCE, CURRENT_DATE()) AS POLICY_TENURE_MONTHS,
  CT.SI_CONSUMED_INR,
  GREATEST(PY.SUM_INSURED_INR + PY.CUMULATIVE_BONUS_INR - CT.SI_CONSUMED_INR, 0)
    AS SI_REMAINING_INR,
  CT.CLAIMS_LAST_3Y,
  COALESCE(MC.DECLARED_PED_COUNT, 0) AS DECLARED_PED_COUNT
FROM POLICY_YEAR PY
JOIN CLAIM_TOTALS CT ON CT.POLICY_ID = PY.POLICY_ID
LEFT JOIN CONDITION_TOTALS MC ON MC.MEMBER_ID = PY.MEMBER_ID;

CREATE OR REPLACE SEMANTIC VIEW MEMBER_360
  TABLES (
    M AS CASHLESSIQ.CORE.MEMBER PRIMARY KEY (MEMBER_ID)
      WITH SYNONYMS ('member', 'insured person'),
    P AS CASHLESSIQ.CORE.POLICY PRIMARY KEY (POLICY_ID)
      WITH SYNONYMS ('policy', 'cover'),
    PP AS CASHLESSIQ.CORE.POLICY_PRODUCT PRIMARY KEY (PRODUCT_ID),
    T AS CASHLESSIQ.CORE.TPA PRIMARY KEY (TPA_ID),
    MC AS CASHLESSIQ.CORE.MEMBER_CONDITION PRIMARY KEY (MEMBER_ID, ICD10_CODE)
      WITH SYNONYMS ('PED', 'pre-existing condition'),
    C AS CASHLESSIQ.CORE.CLAIM PRIMARY KEY (CLAIM_ID)
      WITH SYNONYMS ('claim history'),
    PR AS CASHLESSIQ.DOCS.PREAUTH_REQUEST PRIMARY KEY (REQUEST_ID)
      WITH SYNONYMS ('pre-auth', 'cashless request'),
    PF AS CASHLESSIQ.DOCS.PREAUTH_FACTS PRIMARY KEY (REQUEST_ID),
    PM AS CASHLESSIQ.AI.POLICY_METRICS PRIMARY KEY (POLICY_ID)
  )
  RELATIONSHIPS (
    POLICY_MEMBER AS P (MEMBER_ID) REFERENCES M (MEMBER_ID),
    POLICY_PRODUCT AS P (PRODUCT_ID) REFERENCES PP (PRODUCT_ID),
    POLICY_TPA AS P (TPA_ID) REFERENCES T (TPA_ID),
    CONDITION_MEMBER AS MC (MEMBER_ID) REFERENCES M (MEMBER_ID),
    CLAIM_POLICY AS C (POLICY_ID) REFERENCES P (POLICY_ID),
    PREAUTH_POLICY AS PR (POLICY_ID) REFERENCES P (POLICY_ID),
    PREAUTH_FACTS_REQUEST AS PF (REQUEST_ID) REFERENCES PR (REQUEST_ID),
    METRICS_POLICY AS PM (POLICY_ID) REFERENCES P (POLICY_ID)
  )
  FACTS (
    P.SUM_INSURED_INR AS P.SUM_INSURED_INR
      WITH SYNONYMS ('sum insured', 'SI', 'cover amount'),
    P.CUMULATIVE_BONUS_INR AS P.CUMULATIVE_BONUS_INR,
    C.CLAIMED_INR AS C.CLAIMED_INR,
    C.PAID_INR AS C.PAID_INR,
    PF.ESTIMATED_TOTAL_INR AS PF.ESTIMATED_TOTAL_INR
  )
  DIMENSIONS (
    M.MEMBER_ID AS M.MEMBER_ID,
    M.CITY AS M.CITY,
    M.GENDER AS M.GENDER,
    P.POLICY_ID AS P.POLICY_ID,
    P.STATUS AS P.STATUS,
    P.INCEPTION_DATE AS P.INCEPTION_DATE,
    P.CONTINUOUS_COVER_SINCE AS P.CONTINUOUS_COVER_SINCE,
    PP.PRODUCT_ID AS PP.PRODUCT_ID,
    PP.PRODUCT_NAME AS PP.PRODUCT_NAME,
    T.TPA_ID AS T.TPA_ID,
    T.NAME AS T.NAME,
    MC.ICD10_CODE AS MC.ICD10_CODE,
    MC.CONDITION_NAME AS MC.CONDITION_NAME,
    MC.DECLARED_AT_PROPOSAL AS MC.DECLARED_AT_PROPOSAL,
    C.CLAIM_ID AS C.CLAIM_ID,
    C.ADMISSION_DATE AS C.ADMISSION_DATE,
    C.STATUS AS C.STATUS,
    PR.REQUEST_ID AS PR.REQUEST_ID,
    PR.RECEIVED_AT AS PR.RECEIVED_AT,
    PR.STATUS AS PR.STATUS,
    PF.DIAGNOSIS AS PF.DIAGNOSIS,
    PF.PROCEDURE AS PF.PROCEDURE,
    PF.ADMISSION_DATE AS PF.ADMISSION_DATE
  )
  METRICS (
    PM.POLICY_TENURE_MONTHS AS MAX(PM.POLICY_TENURE_MONTHS),
    PM.SI_CONSUMED_INR AS MAX(PM.SI_CONSUMED_INR)
      WITH SYNONYMS ('used sum insured', 'used SI'),
    PM.SI_REMAINING_INR AS MAX(PM.SI_REMAINING_INR)
      WITH SYNONYMS ('remaining sum insured', 'remaining SI', 'available cover'),
    PM.CLAIMS_LAST_3Y AS MAX(PM.CLAIMS_LAST_3Y)
      WITH SYNONYMS ('claims in the last three years'),
    PM.DECLARED_PED_COUNT AS MAX(PM.DECLARED_PED_COUNT)
      WITH SYNONYMS ('declared PED count', 'pre-existing condition count')
  )
  COMMENT = 'CashlessIQ member, policy, claims, pre-authorisation, and coverage context'
  AI_SQL_GENERATION 'Use integer INR. Use the declared metrics for tenure, consumed SI, remaining SI, three-year claim count, and declared PED count. Never calculate claim payable amounts.'
  AI_VERIFIED_QUERIES (
    REMAINING_SI AS (
      QUESTION 'What is the remaining sum insured for policy POL0001?'
      SQL 'SELECT POLICY_ID, SI_REMAINING_INR FROM CASHLESSIQ.AI.POLICY_METRICS WHERE POLICY_ID = ''POL0001'''
    ),
    CONSUMED_SI AS (
      QUESTION 'How much sum insured has policy POL0001 consumed this policy year?'
      SQL 'SELECT POLICY_ID, SI_CONSUMED_INR FROM CASHLESSIQ.AI.POLICY_METRICS WHERE POLICY_ID = ''POL0001'''
    ),
    POLICY_TENURE AS (
      QUESTION 'What is the policy tenure in months for policy POL0001?'
      SQL 'SELECT POLICY_ID, POLICY_TENURE_MONTHS FROM CASHLESSIQ.AI.POLICY_METRICS WHERE POLICY_ID = ''POL0001'''
    ),
    DECLARED_CONDITIONS AS (
      QUESTION 'Which conditions were declared at proposal for member MEM0001?'
      SQL 'SELECT MEMBER_ID, ICD10_CODE, CONDITION_NAME FROM CASHLESSIQ.CORE.MEMBER_CONDITION WHERE MEMBER_ID = ''MEM0001'' AND DECLARED_AT_PROPOSAL ORDER BY ICD10_CODE'
    ),
    MEMBER_CLAIMS_3Y AS (
      QUESTION 'Show claims in the last three years for member MEM0001.'
      SQL 'SELECT C.CLAIM_ID, C.ADMISSION_DATE, C.CLAIMED_INR, C.PAID_INR, C.STATUS FROM CASHLESSIQ.CORE.CLAIM C JOIN CASHLESSIQ.CORE.POLICY P ON P.POLICY_ID = C.POLICY_ID WHERE P.MEMBER_ID = ''MEM0001'' AND C.ADMISSION_DATE >= DATEADD(YEAR, -3, CURRENT_DATE()) ORDER BY C.ADMISSION_DATE DESC'
    ),
    POLICY_CLAIM_COUNT AS (
      QUESTION 'How many claims has policy POL0001 had in the last three years?'
      SQL 'SELECT POLICY_ID, CLAIMS_LAST_3Y FROM CASHLESSIQ.AI.POLICY_METRICS WHERE POLICY_ID = ''POL0001'''
    ),
    PREAUTH_FOR_POLICY AS (
      QUESTION 'List cashless requests for policy POL0001.'
      SQL 'SELECT REQUEST_ID, RECEIVED_AT, STATUS FROM CASHLESSIQ.DOCS.PREAUTH_REQUEST WHERE POLICY_ID = ''POL0001'' ORDER BY RECEIVED_AT DESC'
    ),
    PREAUTH_FACTS AS (
      QUESTION 'Show the extracted diagnosis and estimate for pre-auth GOL001.'
      SQL 'SELECT REQUEST_ID, DIAGNOSIS, PROCEDURE, ESTIMATED_TOTAL_INR FROM CASHLESSIQ.DOCS.PREAUTH_FACTS WHERE REQUEST_ID = ''GOL001'''
    ),
    POLICY_PRODUCT AS (
      QUESTION 'Which product and TPA apply to policy POL0001?'
      SQL 'SELECT P.POLICY_ID, PP.PRODUCT_NAME, T.NAME AS TPA_NAME FROM CASHLESSIQ.CORE.POLICY P JOIN CASHLESSIQ.CORE.POLICY_PRODUCT PP ON PP.PRODUCT_ID = P.PRODUCT_ID JOIN CASHLESSIQ.CORE.TPA T ON T.TPA_ID = P.TPA_ID WHERE P.POLICY_ID = ''POL0001'''
    ),
    MEMBER_POLICY AS (
      QUESTION 'Show active policies for member MEM0001.'
      SQL 'SELECT POLICY_ID, PRODUCT_ID, SUM_INSURED_INR, STATUS FROM CASHLESSIQ.CORE.POLICY WHERE MEMBER_ID = ''MEM0001'' AND STATUS = ''ACTIVE'' ORDER BY POLICY_ID'
    )
  );

GRANT SELECT ON VIEW CASHLESSIQ.AI.POLICY_METRICS TO ROLE CIQ_APP_USER;
GRANT SELECT ON SEMANTIC VIEW CASHLESSIQ.AI.MEMBER_360 TO ROLE CIQ_APP_USER;

SHOW SEMANTIC VIEWS LIKE 'MEMBER_360' IN SCHEMA CASHLESSIQ.AI;
