USE ROLE CIQ_ADMIN;
USE DATABASE CASHLESSIQ;
USE SCHEMA AI;
USE WAREHOUSE CIQ_WH;

CREATE OR REPLACE PROCEDURE TOOL_GET_CASE(REQUEST_ID VARCHAR) RETURNS VARIANT
LANGUAGE PYTHON RUNTIME_VERSION = '3.11' PACKAGES = ('snowflake-snowpark-python')
IMPORTS = ('@CASHLESSIQ.AI.CIQ_CODE_STAGE/cashlessiq.zip')
HANDLER = 'cashlessiq.procs.tools.tool_get_case' EXECUTE AS CALLER;

CREATE OR REPLACE PROCEDURE TOOL_CHECK_WAITING_PERIODS(REQUEST_ID VARCHAR) RETURNS VARIANT
LANGUAGE PYTHON RUNTIME_VERSION = '3.11' PACKAGES = ('snowflake-snowpark-python')
IMPORTS = ('@CASHLESSIQ.AI.CIQ_CODE_STAGE/cashlessiq.zip')
HANDLER = 'cashlessiq.procs.tools.tool_check_waiting_periods' EXECUTE AS CALLER;

CREATE OR REPLACE PROCEDURE TOOL_COMPUTE_PAYABLE(REQUEST_ID VARCHAR) RETURNS VARIANT
LANGUAGE PYTHON RUNTIME_VERSION = '3.11' PACKAGES = ('snowflake-snowpark-python')
IMPORTS = ('@CASHLESSIQ.AI.CIQ_CODE_STAGE/cashlessiq.zip')
HANDLER = 'cashlessiq.procs.tools.tool_compute_payable' EXECUTE AS CALLER;

CREATE OR REPLACE PROCEDURE TOOL_SLA_STATUS(REQUEST_ID VARCHAR) RETURNS VARIANT
LANGUAGE PYTHON RUNTIME_VERSION = '3.11' PACKAGES = ('snowflake-snowpark-python')
IMPORTS = ('@CASHLESSIQ.AI.CIQ_CODE_STAGE/cashlessiq.zip')
HANDLER = 'cashlessiq.procs.tools.tool_sla_status' EXECUTE AS CALLER;

GRANT USAGE ON PROCEDURE TOOL_GET_CASE(VARCHAR) TO ROLE CIQ_APP_USER;
GRANT USAGE ON PROCEDURE TOOL_CHECK_WAITING_PERIODS(VARCHAR) TO ROLE CIQ_APP_USER;
GRANT USAGE ON PROCEDURE TOOL_COMPUTE_PAYABLE(VARCHAR) TO ROLE CIQ_APP_USER;
GRANT USAGE ON PROCEDURE TOOL_SLA_STATUS(VARCHAR) TO ROLE CIQ_APP_USER;
