USE ROLE ACCOUNTADMIN;

CREATE USER IF NOT EXISTS CIQ_MO_USER
  TYPE = PERSON DEFAULT_ROLE = CIQ_MEDICAL_OFFICER DEFAULT_WAREHOUSE = CIQ_WH
  COMMENT = 'CashlessIQ medical-officer demo persona';
CREATE USER IF NOT EXISTS CIQ_PROC_USER
  TYPE = PERSON DEFAULT_ROLE = CIQ_PROCESSOR DEFAULT_WAREHOUSE = CIQ_WH
  COMMENT = 'CashlessIQ processor demo persona';
CREATE USER IF NOT EXISTS CIQ_AUDIT_USER
  TYPE = PERSON DEFAULT_ROLE = CIQ_AUDITOR DEFAULT_WAREHOUSE = CIQ_WH
  COMMENT = 'CashlessIQ auditor demo persona';
CREATE USER IF NOT EXISTS CIQ_JUDGE
  TYPE = PERSON DEFAULT_ROLE = CIQ_MEDICAL_OFFICER DEFAULT_WAREHOUSE = CIQ_WH
  COMMENT = 'CashlessIQ hackathon judge persona';

GRANT ROLE CIQ_MEDICAL_OFFICER TO USER CIQ_MO_USER;
GRANT ROLE CIQ_PROCESSOR TO USER CIQ_PROC_USER;
GRANT ROLE CIQ_AUDITOR TO USER CIQ_AUDIT_USER;
GRANT ROLE CIQ_MEDICAL_OFFICER TO USER CIQ_JUDGE;

USE ROLE CIQ_ADMIN;
USE DATABASE CASHLESSIQ;
USE SCHEMA GOV;

CREATE OR ALTER MASKING POLICY MASK_CLINICAL_TEXT AS (VAL STRING)
RETURNS STRING ->
  CASE
    WHEN IS_ROLE_IN_SESSION('CIQ_MEDICAL_OFFICER')
      OR IS_ROLE_IN_SESSION('CIQ_ADMIN') THEN VAL
    ELSE '***'
  END
  COMMENT = 'Clinical text is visible only to medical officers and administrators';

CREATE OR ALTER MASKING POLICY MASK_PII AS (VAL STRING)
RETURNS STRING ->
  CASE
    WHEN IS_ROLE_IN_SESSION('CIQ_MEDICAL_OFFICER')
      OR IS_ROLE_IN_SESSION('CIQ_ADMIN') THEN VAL
    WHEN IS_ROLE_IN_SESSION('CIQ_PROCESSOR') THEN
      CASE
        WHEN REGEXP_LIKE(VAL, '^[+0-9 ()-]+$')
          THEN '******' || RIGHT(REGEXP_REPLACE(VAL, '[^0-9]', ''), 4)
        ELSE REGEXP_REPLACE(VAL, '(^| )([[:alpha:]])[[:alpha:]]*', '\\1\\2.')
      END
    ELSE '***'
  END
  COMMENT = 'Medical officer clear; processor partial; auditor fully masked';

ALTER TABLE CASHLESSIQ.DOCS.PREAUTH_FACTS MODIFY COLUMN CLINICAL_NOTE
  SET MASKING POLICY CASHLESSIQ.GOV.MASK_CLINICAL_TEXT FORCE;
ALTER TABLE CASHLESSIQ.CORE.MEMBER MODIFY COLUMN FULL_NAME
  SET MASKING POLICY CASHLESSIQ.GOV.MASK_PII FORCE;
ALTER TABLE CASHLESSIQ.CORE.MEMBER MODIFY COLUMN PHONE
  SET MASKING POLICY CASHLESSIQ.GOV.MASK_PII FORCE;

GRANT SELECT ON ALL TABLES IN SCHEMA CASHLESSIQ.CORE TO ROLE CIQ_APP_USER;
GRANT SELECT ON ALL TABLES IN SCHEMA CASHLESSIQ.DOCS TO ROLE CIQ_APP_USER;
GRANT READ ON STAGE CASHLESSIQ.DOCS.PREAUTH_STAGE TO ROLE CIQ_APP_USER;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA CASHLESSIQ.APP TO ROLE CIQ_APP_USER;
GRANT SELECT ON ALL TABLES IN SCHEMA CASHLESSIQ.EVAL TO ROLE CIQ_APP_USER;
GRANT SELECT ON VIEW CASHLESSIQ.AI.POLICY_METRICS TO ROLE CIQ_APP_USER;
GRANT SELECT ON SEMANTIC VIEW CASHLESSIQ.AI.MEMBER_360 TO ROLE CIQ_APP_USER;
GRANT USAGE ON CORTEX SEARCH SERVICE CASHLESSIQ.AI.CLAUSE_SEARCH TO ROLE CIQ_APP_USER;
GRANT USAGE ON AGENT CASHLESSIQ.AI.CASHLESSIQ_AGENT TO ROLE CIQ_APP_USER;

-- VERIFY WITH COCO: Set authentication for the four demo users using the
-- account's supported method (temporary password, SSO, or programmatic access).
-- Never store those credentials in this repository.
