-- Safe acceptance check: returns labels only, never protected values.
USE SECONDARY ROLES NONE;

USE ROLE CIQ_MEDICAL_OFFICER;
USE WAREHOUSE CIQ_WH;
SELECT
  IFF(FULL_NAME = '***', 'MASKED', 'CLEAR') AS NAME_VIEW,
  IFF(PHONE = '***', 'MASKED', 'CLEAR') AS PHONE_VIEW,
  IFF((SELECT CLINICAL_NOTE FROM CASHLESSIQ.DOCS.PREAUTH_FACTS
       WHERE REQUEST_ID = 'GOL001') = '***', 'MASKED', 'CLEAR') AS CLINICAL_VIEW
FROM CASHLESSIQ.CORE.MEMBER WHERE MEMBER_ID = 'MEM0001';

USE ROLE CIQ_PROCESSOR;
USE WAREHOUSE CIQ_WH;
SELECT
  IFF(FULL_NAME = '***', 'MASKED', IFF(FULL_NAME LIKE '%.%', 'PARTIAL', 'CLEAR'))
    AS NAME_VIEW,
  IFF(PHONE = '***', 'MASKED', IFF(PHONE LIKE '******%', 'PARTIAL', 'CLEAR'))
    AS PHONE_VIEW,
  IFF((SELECT CLINICAL_NOTE FROM CASHLESSIQ.DOCS.PREAUTH_FACTS
       WHERE REQUEST_ID = 'GOL001') = '***', 'MASKED', 'CLEAR') AS CLINICAL_VIEW
FROM CASHLESSIQ.CORE.MEMBER WHERE MEMBER_ID = 'MEM0001';

USE ROLE CIQ_AUDITOR;
USE WAREHOUSE CIQ_WH;
SELECT
  IFF(FULL_NAME = '***', 'MASKED', 'CLEAR') AS NAME_VIEW,
  IFF(PHONE = '***', 'MASKED', 'CLEAR') AS PHONE_VIEW,
  IFF((SELECT CLINICAL_NOTE FROM CASHLESSIQ.DOCS.PREAUTH_FACTS
       WHERE REQUEST_ID = 'GOL001') = '***', 'MASKED', 'CLEAR') AS CLINICAL_VIEW
FROM CASHLESSIQ.CORE.MEMBER WHERE MEMBER_ID = 'MEM0001';
