-- Restricted caller-rights allow each viewer's default role to drive masking.
USE ROLE ACCOUNTADMIN;

GRANT USAGE ON COMPUTE POOL SYSTEM_COMPUTE_POOL_CPU TO ROLE CIQ_ADMIN;
-- Snowflake does not support transferring ownership of this container Streamlit
-- with GRANT OWNERSHIP. Deploy/recreate it with CIQ_ADMIN so that role owns it.

GRANT CALLER USAGE ON DATABASE CASHLESSIQ TO ROLE CIQ_ADMIN;
GRANT CALLER USAGE ON SCHEMA CASHLESSIQ.CORE TO ROLE CIQ_ADMIN;
GRANT CALLER USAGE ON SCHEMA CASHLESSIQ.DOCS TO ROLE CIQ_ADMIN;
GRANT CALLER USAGE ON SCHEMA CASHLESSIQ.AI TO ROLE CIQ_ADMIN;
GRANT CALLER USAGE ON SCHEMA CASHLESSIQ.APP TO ROLE CIQ_ADMIN;

GRANT CALLER SELECT ON TABLE CASHLESSIQ.CORE.HOSPITAL TO ROLE CIQ_ADMIN;
GRANT CALLER SELECT ON TABLE CASHLESSIQ.CORE.POLICY TO ROLE CIQ_ADMIN;
GRANT CALLER SELECT ON TABLE CASHLESSIQ.CORE.MEMBER TO ROLE CIQ_ADMIN;
GRANT CALLER SELECT ON TABLE CASHLESSIQ.CORE.MEMBER_CONDITION TO ROLE CIQ_ADMIN;
GRANT CALLER SELECT ON TABLE CASHLESSIQ.CORE.CLAIM TO ROLE CIQ_ADMIN;
GRANT CALLER SELECT ON TABLE CASHLESSIQ.DOCS.PREAUTH_REQUEST TO ROLE CIQ_ADMIN;
GRANT CALLER SELECT ON TABLE CASHLESSIQ.DOCS.PREAUTH_FACTS TO ROLE CIQ_ADMIN;
GRANT CALLER SELECT ON TABLE CASHLESSIQ.DOCS.POLICY_CLAUSE TO ROLE CIQ_ADMIN;
GRANT CALLER READ ON STAGE CASHLESSIQ.DOCS.PREAUTH_STAGE TO ROLE CIQ_ADMIN;
GRANT CALLER SELECT, INSERT ON TABLE CASHLESSIQ.APP.DECISION TO ROLE CIQ_ADMIN;
GRANT CALLER SELECT, INSERT ON TABLE CASHLESSIQ.APP.REVIEW_ACTION TO ROLE CIQ_ADMIN;
GRANT CALLER SELECT ON VIEW CASHLESSIQ.AI.POLICY_METRICS TO ROLE CIQ_ADMIN;
GRANT CALLER SELECT ON SEMANTIC VIEW CASHLESSIQ.AI.MEMBER_360 TO ROLE CIQ_ADMIN;
GRANT CALLER USAGE ON CORTEX SEARCH SERVICE CASHLESSIQ.AI.CLAUSE_SEARCH TO ROLE CIQ_ADMIN;
GRANT CALLER USAGE ON AGENT CASHLESSIQ.AI.CASHLESSIQ_AGENT TO ROLE CIQ_ADMIN;
GRANT CALLER USAGE ON PROCEDURE CASHLESSIQ.AI.TOOL_GET_CASE(VARCHAR) TO ROLE CIQ_ADMIN;
GRANT CALLER USAGE ON PROCEDURE CASHLESSIQ.AI.TOOL_CHECK_WAITING_PERIODS(VARCHAR)
  TO ROLE CIQ_ADMIN;
GRANT CALLER USAGE ON PROCEDURE CASHLESSIQ.AI.TOOL_COMPUTE_PAYABLE(VARCHAR)
  TO ROLE CIQ_ADMIN;
GRANT CALLER USAGE ON PROCEDURE CASHLESSIQ.AI.TOOL_SLA_STATUS(VARCHAR) TO ROLE CIQ_ADMIN;
