-- Destructive by design: removes only CashlessIQ-owned objects.
USE ROLE ACCOUNTADMIN;

DROP AGENT IF EXISTS CASHLESSIQ.AI.CIQ_SPIKE_AGENT;
DROP DATABASE IF EXISTS CASHLESSIQ;
DROP WAREHOUSE IF EXISTS CIQ_WH;
DROP RESOURCE MONITOR IF EXISTS CIQ_RM;

DROP ROLE IF EXISTS CIQ_AUDITOR;
DROP ROLE IF EXISTS CIQ_PROCESSOR;
DROP ROLE IF EXISTS CIQ_MEDICAL_OFFICER;
DROP ROLE IF EXISTS CIQ_APP_USER;
DROP ROLE IF EXISTS CIQ_ADMIN;
